#!/bin/bash
echo "Server Name"
read name
echo "Server IP"
read ip
echo "Server ID"
read id

rm "cfg/server.cfg"
rm "cfg/sourcemod/get5.cfg"
rm "cfg/sourcemod/discord_calladmin.cfg"

echo '
// League Ops Template Config
// Created by: bjerrecs

// ==============================================================================
// Server Name, RCON Password & SV Passowrd
// ==============================================================================
hostname "'$name'"
rcon_password "TyCA23"
sv_password ""

// ==============================================================================
// Server CVARs
// ==============================================================================
mp_autoteambalance "0"
mp_autokick "0"
sv_pausable "0"
mp_limitteams "0"
sv_allow_lobby_connect_only "0"
sv_forcepreload "1"
sv_pure "1" //This will force players to use default models
sv_consistency "0"

// ==============================================================================
// Server Rates
// ==============================================================================
sv_maxcmdrate "0"
sv_maxrate "0"
sv_mincmdrate "128000"
sv_minrate "30000"

// ==============================================================================
// logging on
// ==============================================================================
sv_log_onefile "0"
sv_logbans "0"
sv_logecho "1"
sv_logfile "1"
sv_logflush "0"
sv_logsdir "0"
log on

// ==============================================================================
// Voting Options
// ==============================================================================
sv_allow_votes "1"
sv_vote_allow_in_warmup "1"
sv_vote_allow_spectators "1"
sv_vote_command_delay "5"
sv_vote_creation_time "1"
sv_vote_issue_loadbackup_allowed "1"
sv_vote_failure_timer "1"
sv_vote_quorum_ratio "0"
sv_vote_timer_duration "15"
mp_endmatch_votenextmap "0"
sv_vote_issue_restart_game_allowed "1"
mp_team_timeout_time "30"
mp_team_timeout_max "4"

// ==============================================================================
//  Competitive CVARs
//  Disables drops, auto pause match if all players not connected, enables 5v5 stats
// ==============================================================================
sv_matchend_drops_enabled "0"
sv_matchpause_auto_5v5 "0"
sv_competitive_official_5v5 "1"

// ==============================================================================
//  Mandetory exec of banned users
// ==============================================================================
sv_lan "0"
sv_region "255"
sv_downloadurl "" //Add http site to donwload from
sv_allowdownload 0
sv_allowupload 0
writeid
writeip
exec banned_user.cfg
exec banned_ip.cfg
exec gotv.cfg

' >> cfg/server.cfg

echo '
// This file was auto-generated by SourceMod (v1.10.0.6536)
// ConVars for plugin "get5.smx"


// Whether or not technical pauses are allowed
// -
// Default: "1"
get5_allow_technical_pause "1"

// Whether to automatically mark players as ready if they kill anyone in the warmup or veto phase.
// -
// Default: "0"
get5_auto_ready_active_players "0"

// Name of a match config file to automatically load when the server loads
// -
// Default: ""
get5_autoload_config ""

// Whether the get5 backup system is enabled
// -
// Default: "1"
get5_backup_system_enabled "1"

// If set to 0, get5 will not force players to the correct team based on steamid
// -
// Default: "1"
get5_check_auths "1"

// Format of the damage output string. Avaliable tags are in the default, color tags such as {LIGHT_RED} and {GREEN} also work.
// -
// Default: "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"
get5_damageprint_format "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"

// Format for demo file names, use "" to disable
// -
// Default: "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"
get5_demo_name_format "{MATCHID}_{TEAM1}_-_{TEAM2}_map{MAPNUMBER}_{MAPNAME}"

// Whether to wait for map vetos to be printed to GOTV before changing map
// -
// Default: "0"
get5_display_gotv_veto "0"

// Whether to end the match if all players disconnect before ending. No winner is set if this happens.
// -
// Default: "0"
get5_end_match_on_empty_server "1"

// Path to use when writing match event logs, use "" to disable
// -
// Default: ""
get5_event_log_format ""

// If set to non-zero, this will be the fixed length of any pause
// -
// Default: "0"
get5_fixed_pause_time "30"

// Template that the server hostname will follow when a match is live. Leave field blank to disable. Valid parameters are: {MAPNUMBER}, {MATCHID}, {SERVERID}, {MAPNAME}, {TIME}, {TEAM1}, {TEAM2}
// -
// Default: "Get5: {TEAM1} vs {TEAM2}"
get5_hostname_format "AFTI: {TEAM1} vs {TEAM2}"

// Whether or not admins with the changemap flag will be immune to kicks from "get5_kick_when_no_match_loaded". Set to "0" to disable
// -
// Default: "1"
get5_kick_immunity "1"

// Whether the plugin kicks new clients when no match is loaded
// -
// Default: "0"
get5_kick_when_no_match_loaded "0"

// Config file to exec when the game goes live
// -
// Default: "get5/live.cfg"
get5_live_cfg "get5/live.cfg"

// Number of seconds used to count down when a match is going live
// -
// Default: "10"
// Minimum: "5.000000"
// Maximum: "60.000000"
get5_live_countdown_time "10"

// Number of seconds before a backup file is automatically deleted, 0 to disable
// -
// Default: "160000"
get5_max_backup_age "160000"

// Maximum number of time the game can spend paused by a team, 0=unlimited
// -
// Default: "300"
get5_max_pause_time "300"

// Maximum number of pauses a team can use, 0=unlimited
// -
// Default: "0"
get5_max_pauses "4"

// The tag applied before plugin messages.
// -
// Default: "[{YELLOW}Get5{NORMAL}]"
get5_message_prefix "[{YELLOW}AFTI{NORMAL}]"

// Whether pausing is allowed.
// -
// Default: "1"
get5_pausing_enabled "1"

// Whether all JSON output is in pretty-print format.
// -
// Default: "1"
get5_pretty_print_json "1"

// Whether damage reports are printed on round end.
// -
// Default: "0"
get5_print_damage "1"

// Adds [READY] [NOT READY] Tags before Team Names. 0 to disable it.
// -
// Default: "1"
get5_ready_team_tag "1"

// Whether pause limits will be reset each halftime period
// -
// Default: "1"
get5_reset_pauses_each_half "0"

// Integer that identifies your server. This is used in temp files to prevent collisions.
// -
// Default: "0"
get5_server_id "'$id'"

// Whether to set client clan tags to player ready status.
// -
// Default: "1"
get5_set_client_clan_tags "1"

// Where match stats are saved (updated each map end), set to "" to disable
// -
// Default: "get5_matchstats_{MATCHID}.cfg"
get5_stats_path_format "get5_matchstats_{MATCHID}.cfg"

// Whether clients can use the !stop command to restore to the last round
// -
// Default: "1"
get5_stop_command_enabled "1"

// Time format to use when creating file names. Don't tweak this unless you know what you're doing! Avoid using spaces or colons.
// -
// Default: "%Y-%m-%d_%H"
get5_time_format "%Y-%m-%d_%H"

// Time (in seconds) a team has to make a !stay/!swap decision after winning knife round, 0=unlimited
// -
// Default: "60"
get5_time_to_make_knife_decision "60"

// Time (in seconds) teams have to ready up before forfeiting the match, 0=unlimited
// -
// Default: "0"
get5_time_to_start "600"

// Time (in seconds) from presenting a veto menu to a selection being made, during which a confirmation will be required, 0 to disable
// -
// Default: "2.0"
get5_veto_confirmation_time "2.0"

// Seconds to countdown before veto process commences. Set to "0" to disable.
// -
// Default: "5"
get5_veto_countdown "5"

// Config file to exec in warmup periods
// -
// Default: "get5/warmup.cfg"
get5_warmup_cfg "get5/warmup.cfg"

get5_upload_demos "1"

' >> cfg/sourcemod/get5.cfg

echo '
// This file was auto-generated by SourceMod (v1.10.0.6536)
// ConVars for plugin "discord_calladmin.smx"


// Report botname, leave this blank to use the webhook default name.
// -
// Default: ""
discord_calladmin_botname "Need Admin"

// Message to send when admin uses the claim command.
// -
// Default: "An admin is claiming reports on this server."
discord_calladmin_claimmsg "Un admin est sur le server."

// Discord/Slack attachment color used for reports.
// -
// Default: "#ff2222"
discord_calladmin_color "#ff2222"

// Discord/Slack attachment color used for admin claims.
// -
// Default: "#22ff22"
discord_calladmin_color2 "#22ff22"

// Discord/Slack attachment color used for admin reports.
// -
// Default: "#ff9911"
discord_calladmin_color3 "#ff9911"

// Set your server IP here when auto detection is not working for you. (Use 0.0.0.0 to disable manually override)
// -
// Default: "0.0.0.0"
discord_calladmin_ip "'$ip'"

// This allows you to mention reports, leave blank to disable.
// -
// Default: "@here"
discord_calladmin_mention "@here"

// Remove this part from servername before sending the report.
// -
// Default: " | By PulseServers.com"
discord_calladmin_remove " | By PulseServers.com"

// Remove this part from servername before sending the report.
// -
// Default: "3kliksphilip.com | "
discord_calladmin_remove2 "3kliksphilip.com | "

// Config key from configs/discord.cfg.
// -
// Default: "calladmin"
discord_calladmin_webhook "calladmin"



' >> cfg/sourcemod/discord_calladmin.cfg
